# Generated by Django 6.0.6 on 2026-06-27 03:55

import uuid
from django.db import migrations, models


def generate_short_codes(apps, schema_editor):
    QRCode = apps.get_model('qrapp', 'QRCode')
    for qr in QRCode.objects.all():
        qr.short_code = uuid.uuid4().hex[:6]
        qr.save(update_fields=['short_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_qrcode_is_active_qrcode_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(generate_short_codes),
        migrations.AlterField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
